config/routes.rb
Rails.application.routes.draw do
  root 'weather#index'
  get 'weather/index'
  get 'fetch_weather', to: 'weather#fetch_weather'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController
  require 'net/http'
  require 'json'

  def index
    # landing page 
  end

  # this method will call the weather api
  

  def fetch_weather
    city = params[:city]
    return render js: "alert('Please enter a ZIP code');" if city.blank?
    api_key = ENV['WEATHER_API_KEY']
    base_url = ENV['WEATHER_API_URL']
    url = "#{base_url}?q=#{city}&units=metric&appid=#{api_key}"
    cache_key = "weather_forecast_#{city}"
    @cached = true
    @weather = Rails.cache.fetch(cache_key, expires_in: 30.minutes) do
      @cached = false
      response = HTTParty.get(url)
      JSON.parse(response.body)
    end
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weather_helper.rb
module WeatherHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weatherforecast</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/weather/fetch_weather.js.erb
<% if @weather.present? %>
  <% if @weather['cod'].to_s == '404' %>
    document.querySelector(".error").style.display = "block";
    document.querySelector(".weather").style.display = "none";
  <% else %>
    document.getElementById("cityName").textContent = "<%= j @weather['name'] %>";
    document.getElementById("temp").textContent = "<%= @weather.dig('main', 'temp') || '--' %>°C";
    document.getElementById("mintemp").textContent = "<%= @weather.dig('main', 'temp_min') || '--' %>°C";
    document.getElementById("maxtemp").textContent = "<%= @weather.dig('main', 'temp_max') || '--' %>°C";
    document.getElementById("humidity").textContent = "<%= @weather.dig('main', 'humidity') || '--' %>%";
    document.getElementById("wind").textContent = "<%= @weather.dig('wind', 'speed') || '--' %> km/h";

    <% icon = case @weather.dig('weather', 0, 'main')
             when 'Clouds' then 'clouds.png'
             when 'Clear'  then 'clear.png'
             when 'Rain', 'Drizzle' then 'rain.png'
             when 'Mist'   then 'mist.png'
             else 'default.png'
             end %>

    document.querySelector(".weather-icon").src = "assets/<%= icon %>";
    document.querySelector(".error").style.display = "none";
    document.querySelector(".weather").style.display = "block";
      document.getElementById("cacheStatus").textContent = "<%= @cached ? '🔁 Cached data (valid for 30 minutes)' : '📡 Live data from API' %>";
  <% end %>
<% else %>
  alert(" Weather data not available.");
<% end %>

app/views/weather/index.html.erb
<div class="card">
<%= form_tag(fetch_weather_path, method: :get, remote: true, id: 'weatherForm') do %>
  <div class="search">
    <%= text_field_tag :city, nil, placeholder: 'Enter city name or the zipcode', id: 'cityInput', spellcheck: false %>
    <button type="submit"><%=image_tag 'search.png' %></button>
  </div>
<% end %>

<div class="error" style="display: none;">
  <h4 style="color:red">Invalid City Name or zipcode</h4>
</div>

<h4 id="cacheStatus" style="font-size: 14px; color: white;"></h4>


<div class="weather" style="display: none;">
<%= image_tag 'rain.png', class: 'weather-icon', id: 'weatherIcon' %>
  <h1 class="temp" id="temp">--°C</h1>
  <p>Min Temp<h4 class="mintemp" id="mintemp">--°C</h4></p>
  <p>Max Temp<h4 class="maxtemp" id="maxtemp">--°C</h4></p>
  <h2 class="city" id="cityName">--</h2>
  <div class="details">
    <div class="col">
            <%= image_tag 'humidity.png' %>

      <div>
        <p class="humidity" id="humidity">--%</p>
        <p>Humidity</p>
      </div>
    </div>
    <div class="col">
      <div>
        <p class="wind" id="wind">-- km/h</p>
        <p>Wind Speed</p>
      </div>
    </div>
  </div>
</div>
</div>